version: '3'
services:
  authserver:
    image: osixia/openldap:1.4.0
    command: ['--copy-service']
    environment:
      LDAP_ORGANISATION: GeoMUD
      LDAP_DOMAIN: jnp2.mimuw.edu.pl
      LDAP_ADMIN_PASSWORD: 'you?know?nothing...'
    volumes:
      - ./auth:/container/service/slapd/assets/config/bootstrap/ldif/custom
    networks:
      - overlay

  authadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: authserver
    ports:
      - "10443:443"
    networks:
      - overlay

  camel:
    build: camel-router/.
    volumes:
      - ./camel-router:/io
    networks:
      - overlay

  mud:
    build: ./mud
    ports:
      - "10023:10023"
    command: ['camel:8082']
    volumes:
      - ./mud:/home/mud
    networks:
      - overlay

  locdb:
    image: kartoza/postgis
    volumes:
      - ./locations/sql:/docker-entrypoint-initdb.d
      - geomud-locations-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
    networks:
      - overlay

  locserver:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: locdb
    volumes:
      - ./locations:/app
    networks:
      - overlay

  wiki:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    volumes:
      - ./wiki:/app
    networks:
      - overlay

networks:
  overlay:
volumes:
  geomud-locations-data:
